// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3e89qVCRZeWYhRDWXw6IOKnsMBl6BPw',
    appId: '1:570733993714:web:49c8cc90ef7feb2c02fa6b',
    messagingSenderId: '570733993714',
    projectId: 'aqua-38d4a',
    authDomain: 'aqua-38d4a.firebaseapp.com',
    storageBucket: 'aqua-38d4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeBFlBNy_k8fQOZb9QLKmd2XkfilLY_A',
    appId: '1:570733993714:android:a4823e79665daf8702fa6b',
    messagingSenderId: '570733993714',
    projectId: 'aqua-38d4a',
    storageBucket: 'aqua-38d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPVpbE6Fml6i5YxFDxzkIM77sIHDrwCuU',
    appId: '1:570733993714:ios:0bd7bb4366323ccd02fa6b',
    messagingSenderId: '570733993714',
    projectId: 'aqua-38d4a',
    storageBucket: 'aqua-38d4a.appspot.com',
    iosClientId: '570733993714-gp53rosi667uut55ohs0qoad25qe69gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPVpbE6Fml6i5YxFDxzkIM77sIHDrwCuU',
    appId: '1:570733993714:ios:0bd7bb4366323ccd02fa6b',
    messagingSenderId: '570733993714',
    projectId: 'aqua-38d4a',
    storageBucket: 'aqua-38d4a.appspot.com',
    iosClientId: '570733993714-gp53rosi667uut55ohs0qoad25qe69gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf3e89qVCRZeWYhRDWXw6IOKnsMBl6BPw',
    appId: '1:570733993714:web:19ab9c720c00fc4102fa6b',
    messagingSenderId: '570733993714',
    projectId: 'aqua-38d4a',
    authDomain: 'aqua-38d4a.firebaseapp.com',
    storageBucket: 'aqua-38d4a.appspot.com',
  );

}